kind: Service
apiVersion: v1
metadata:
  name: codefornl-pipeline
spec:
  selector:
    app: codefornl-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codefornl-staging
  labels:
    app: codefornl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codefornl-web
  template:
    metadata:
      labels:
        app: codefornl-web
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: codefornl-web
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
